### ISSUE TITLE
Unable to infer complex closure return type; add explicit type to disambiguate

### ISSUE THREAD

**Issue by amuresia** [RaffiKian/RKCalendar#3]
Hi @RaffiKian, thank you so much for sharing this project with us!

When trying to compile this project in Xcode beta 5, the following error pops up:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/16068752/63051777-c097dc00-bed5-11e9-9b78-d5dea14ae169.png">
Would you be so kind to assist and suggest a fix? Thank you!

**Comment by workingDog** [comment]
yes great project. Have a look at my pull request (xcode beta 5 and multi-dates) to fix your issue.

**Comment by amuresia** [comment]
Thank you @workingDog! Great work. It works like a charm 👍
